name: phy-unc
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - wandb
    - altair
    - jupyterlab
    - networkx
    - numpy
    - scipy
    - torch
    - gpytorch
    - torchdiffeq
    - "git+https://github.com/mfinzi/olive-oil-ml#egg=olive-oil-ml"
