name: phy-unc
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  # - vega-cli
  # - vega-lite-cli
  # - cairosvg
  - pip:
    - fire
    - wandb
    - altair
    - altair_saver
    - seaborn
    - jupyterlab
    - ipywidgets
    - networkx
    - numpy
    - scipy
    - torch
    - gpytorch
    - torchdiffeq
    - "git+https://github.com/mfinzi/olive-oil-ml#egg=olive-oil-ml"
    - pathos
