## W&B Sample sweep config

# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

method: random
parameters:
  network:
    value: CHNN
  lr:
    value: 0.01
  tau:
    values: [3., 4., 5., 6.]
  C:
    values: [5, 10, 15]
program: exps/run.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}