method: grid
parameters:
  num_bodies:
    value: 3
  lr:
    value: 3e-3
  tau:
    value: 10.0
  C:
    value: 25
  num_epochs:
    value: 50
  swag_epochs:
    value: 20
  eps_scale:
    value: 1e-2
  uq_type:
    value: swag
  noise_rate:
    values: [0.0, 0.01, 0.1, 0.5, 1.0, 2.0]
  # n_subsample:
  #   value: 1000
program: exps/train_chnn.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}