method: grid
parameters:
  num_bodies:
    value: 3
  lr:
    value: 3e-3
  tau:
    value: 10.0
  C:
    value: 25
  num_epochs:
    value: 50
  eps_scale:
    value: 1e-2
  uq_type:
    value: output-uncertainty
  # noise_rate:
  #   values: [0.0, 0.01, 0.05, 0.1, 0.25]
  # n_subsample:
  #   values: [10, 20, 50, 100, 200, 500, 800, 1000]
program: exps/train_chnn.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}