## W&B Sample sweep config

# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

project: physics-uncertainty-exps
method: grid
parameters:
  num_bodies:
    value: 2
  lr:
    value: 3e-3
  tau:
    value: 10.
  C:
    value: 25 
  num_epochs:
    value: 50
  uq_type:
    value: "deep-ensemble"
  noise_rate:
    values: [0, 0.01, 0.1, 1.0]
program: exps/train_chnn.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}