## W&B Sample sweep config

# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

project: physics-uncertainty-exps
method: grid
parameters:
  num_bodies:
    value: 2
  lr:
    value: 3e-3
  tau:
    value: 10.
  C:
    value: 25 
  num_epochs:
    value: 50
  uq_type:
    values: ["det", "swag", "deep-ensemble"]
  n_subsample:
    values: [10, 50, 100, 500, 1000, 5000, 10000]
program: exps/train_chnn.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}