## W&B Sample sweep config

# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

method: grid
parameters:
  num_bodies:
    value: 2
  lr:
    value: 0.01
  tau:
    values: [3., 4., 5., 6.]
  C:
    values: [5, 10, 15]
  num_epochs:
    value: 50
program: exps/train_chnn.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}